/**
 * TypeScript Interface Generation
 * Generates TypeScript interface strings from schema definitions
 * @author The Base Event Team
 * @since 1.0.0
 */

import type { Schema } from "./schemas";

export interface InterfaceOptions {
  interfaceName?: string;
  exportInterface?: boolean;
  rootType?: string;
  addTimestamp?: boolean;
  namespace?: string;
}

interface GeneratedProperty {
  name: string;
  type: string;
  optional: boolean;
  comment?: string;
}

export interface EnumDefinition {
  name: string;
  values: (string | number)[];
}

export function generateInterface(
  schema: Schema,
  options: InterfaceOptions = {}
): string {
  const {
    interfaceName = "GeneratedEvent",
    exportInterface = true,
    namespace,
  } = options;

  const properties = extractProperties(schema, "");
  const prefix = exportInterface ? "export " : "";

  let result = `${prefix}interface ${interfaceName}`;

  if (namespace) {
    result = `${prefix}interface ${namespace}.${interfaceName}`;
  }

  result += " {\n";

  for (const prop of properties) {
    const optionalMark = prop.optional ? "?" : "";
    const comment = prop.comment ? `  // ${prop.comment}\n` : "";
    result += `${comment}  ${prop.name}${optionalMark}: ${prop.type};\n`;
  }

  result += "}";

  return result;
}

function extractProperties(schema: Schema, path: string): GeneratedProperty[] {
  const properties: GeneratedProperty[] = [];

  switch (schema.type) {
    case "object":
      if (schema.properties) {
        for (const [name, propSchema] of Object.entries(schema.properties)) {
          const required =
            schema.required && schema.required.includes(name) ? false : true;
          const type = schemaTypeToTs(propSchema, path + name);
          properties.push({
            name,
            type,
            optional: required,
          });
        }
      }
      break;

    case "array": {
      const itemType = schemaTypeToTs(schema.items, `${path}[]`);
      properties.push({
        name: "items",
        type: `${itemType}[]`,
        optional: true,
      });
      break;
    }

    case "string":
    case "number":
    case "boolean":
      properties.push({
        name: "value",
        type: schemaTypeToTs(schema, path),
        optional: !schema.optional,
      });
      break;

    default:
      properties.push({
        name: "value",
        type: "unknown",
        optional: true,
      });
  }

  return properties;
}

export function schemaTypeToTs(schema: Schema, path: string): string {
  if (schema.type === "string") {
    if (schema.enum && schema.enum.length > 0) {
      return schema.enum.map(v => `"${v}"`).join(" | ");
    }
    return "string";
  }

  if (schema.type === "number") {
    if (schema.enum && schema.enum.length > 0) {
      return schema.enum.join(" | ");
    }
    return "number";
  }

  if (schema.type === "boolean") {
    return "boolean";
  }

  if (schema.type === "object") {
    if (schema.properties && Object.keys(schema.properties).length > 0) {
      const props: string[] = [];
      for (const [name, propSchema] of Object.entries(schema.properties)) {
        const optional =
          schema.required && schema.required.includes(name) ? "" : "?";
        const propType = schemaTypeToTs(propSchema, `${path}.${name}`);
        props.push(`  ${name}${optional}: ${propType};`);
      }
      return `{\n${props.join("\n")}\n}`;
    }
    return "Record<string, unknown>";
  }

  if (schema.type === "array") {
    const itemType = schemaTypeToTs(schema.items, `${path}Item`);
    return `${itemType}[]`;
  }

  if (schema.type === "enum") {
    if (typeof schema.values[0] === "string") {
      return schema.values.map(v => `"${v}"`).join(" | ");
    }
    return schema.values.join(" | ");
  }

  if (schema.type === "union") {
    return schema.schemas.map(s => schemaTypeToTs(s, path)).join(" | ");
  }

  if (schema.type === "literal") {
    return JSON.stringify(schema.value);
  }

  return "unknown";
}

export function generateInterfaceFile(
  schemas: { channel: string; schema: Schema }[],
  options: InterfaceOptions = {}
): string {
  const { namespace = "EventSchemas" } = options;

  const interfaces: string[] = [];

  for (const { channel, schema } of schemas) {
    const interfaceName = channelToInterfaceName(channel);
    const interfaceStr = generateInterface(schema, {
      ...options,
      interfaceName,
      namespace,
    });
    interfaces.push(interfaceStr);
  }

  return `// Auto-generated TypeScript interfaces\n// Generated by The Base Event\n\n${interfaces.join("\n\n")}`;
}

function channelToInterfaceName(channel: string): string {
  return channel
    .split(/[:.]/)
    .map(segment => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join("");
}

export function generateEnum(
  name: string,
  values: (string | number)[],
  options: { export?: boolean; prefix?: string } = {}
): string {
  const { export: exp = true, prefix } = options;
  const prefixStr = prefix || "";
  const exportStr = exp ? "export " : "";

  if (typeof values[0] === "string") {
    const enumMembers = values
      .map(v => `  ${prefixStr}${(v as string).toUpperCase()} = "${v}"`)
      .join(",\n");
    return `${exportStr}enum ${name} {\n${enumMembers}\n}`;
  } else {
    const typeMembers = values
      .map(v => `  ${prefixStr}${v} = ${v}`)
      .join(",\n");
    return `${exportStr}enum ${name} {\n${typeMembers}\n}`;
  }
}

export function generateTypeAlias(
  name: string,
  type: string,
  options: { export?: boolean } = {}
): string {
  const { export: exp = true } = options;
  const exportStr = exp ? "export " : "";
  return `${exportStr}type ${name} = ${type};`;
}

export function generateUnionType(types: string[], name?: string): string {
  const unionStr = types.join(" | ");
  if (name) {
    return `type ${name} = ${unionStr};`;
  }
  return unionStr;
}

export function generateGenericInterface(
  name: string,
  typeParameter: string,
  constraint?: string,
  options: { export?: boolean } = {}
): string {
  const { export: exp = true } = options;
  const exportStr = exp ? "export " : "";
  const constraintStr = constraint ? ` extends ${constraint}` : "";
  return `${exportStr}interface ${name}<${typeParameter}${constraintStr}> {}`;
}

export function addComment(
  text: string,
  comment: string,
  position: "above" | "inline" = "above"
): string {
  if (position === "above") {
    return `/** ${comment} */\n${text}`;
  }
  return `${text} // ${comment}`;
}

export interface TypeDef {
  name: string;
  type: string;
  comment?: string;
}

export function generateTypeDefs(typeDefs: TypeDef[]): string {
  return typeDefs
    .map(def => {
      const comment = def.comment ? `  // ${def.comment}\n  ` : "  ";
      return `${comment}readonly ${def.name}: ${def.type};`;
    })
    .join("\n");
}

export function generateEventInterface(
  channel: string,
  dataSchema: Schema,
  options: InterfaceOptions = {}
): string {
  const { interfaceName, exportInterface = true } = options;

  const dataType = schemaTypeToTs(dataSchema, "data");
  const name = interfaceName || channelToInterfaceName(channel);

  const exportStr = exportInterface ? "export " : "";

  return `${exportStr}interface ${name} {
  readonly id: string;
  readonly channel: "${channel}";
  readonly data: ${dataType};
  readonly timestamp: number;
  readonly version?: string;
  readonly type?: string;
}`;
}
